PyTorch 主模块也有提供很多功能……虽然还远没有 Tensor、Module 这些概念重要。

In [1]:
import torch

a = torch.rand(2)
a

tensor([0.8654, 0.0211])

In [9]:
# torch.repeat_interleave(input, repeats, dim=None, *, output_size=None)
# This is different from torch.Tensor.repeat() but similar to numpy.repeat.
# 用于在指定维度上对张量进行复制和重复操作。
a = torch.repeat_interleave(torch.rand(1), 5)
b = torch.repeat_interleave(torch.rand(3), 3)
a, b

(tensor([0.4933, 0.4933, 0.4933, 0.4933, 0.4933]),
 tensor([0.2460, 0.2460, 0.2460, 0.0950, 0.0950, 0.0950, 0.2524, 0.2524, 0.2524]))